apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fedi-discover
resources:
- fedi-studio-firehose-deployment.yaml
- fedi-studio-sync-v1-to-v2-deployment.yaml
- fedi-studio-lead-crawler-deployment.yaml
- fedi-studio-web-deployment.yaml
- fedi-studio-pull-tim-outbox-deployment.yaml
- candidate-finder-deployment.yaml
